### ISSUE TITLE
Is this GPL3 or MIT?

### ISSUE THREAD

**Issue by dsrw** [warriormaster12/Godot-Sci-fi_AssetPack#2]
Thanks for making this. I saw a post about it on reddit and it looks great.

The project contains 2 licences. GPL3 at the root of the project, and MIT in the Sci-fi_AssetPack directory. Which is it?

I'm hoping you go with MIT, as I won't be able to use it if it's GPL3, but you do what's right for you of course. Thanks!

**Comment by warriormaster12** [comment]
@dsrw I selected GPL 3 since I thought that it was more fair towards the original creator and people who use it can use it for commercial use. 

If you have arguments against GPL 3 then please tell me. I would be happy to hear them :D

**Comment by warriormaster12** [comment]
Actually now I see a problem with GPL 3. I'll switch it to MIT

**Comment by warriormaster12** [comment]
Thanks for bringing this up. The project is now under MIT license since I want that people can freely make game projects without necessity to share the source code to the public.

**Comment by dsrw** [comment]
Thank you!
